"""
Token Mappings Configuration File
================================

This file is AUTO-GENERATED from tokens.csv
DO NOT EDIT THIS FILE MANUALLY

To update token mappings:
1. Edit data/tokens.csv
2. Run: python3 scripts/v2.0/generate_token_mappings.py

Generated on: 2026-02-22 18:10:24
"""

# Address to token name mappings (auto-generated from tokens.csv)
ADDRESS_MAPPINGS = {
    '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9': 'Aave',
    '0x3506424f91fd33084466f402d5d97f05f8e3b4af': 'Chiliz',
    '0xc00e94cb662c3520282e6f5717214004a7f26888': 'Compound',
    '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48': 'USD Coin',
    '0xdac17f958d2ee523a2206206994597c13d831ec7': 'Tether',
    '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599': 'Wrapped Bitcoin',
    '0x514910771af9ca656af840dff83e8264ecf986ca': 'Chainlink',
    '0x111111111117dc0aa78b770fa6a738034120c302': '1inch',
    '0xf230b790e05390fc8295f4d3f60332c93bed42e2': 'Tron',
    '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984': 'Uniswap',
    '0x6b175474e89094c44da98b954eedeac495271d0f': 'Dai',
    '0xc944e90c64b2c07662a292be6244bdf05cda44a7': 'The Graph',
    '0x56072c95faa701256059aa122697b133aded9279': 'Sky',
    '0x6b3595068778dd592e39a122f4f5a5cf09c90fe2': 'SushiSwap',
    '0x4a220e6096b25eadb88358cb44068a3248254675': 'Quant',
    '0x15d4c048f83bd7e37d49ea4c83a07267ec4203da': 'Gala',
    '0x0f5d2fb29fb7d3cfee444a200298f468908cc942': 'Decentraland',
    '0x3845badade8e6dff049820680d1f14bd3903a5d0': 'Sandbox',
    '0x0d8775f648430679a709e98d2b0cb6250d2887ef': 'Basic Attention Token',
    '0x455e53cbb86018ac2b8092fdcd39d8444affc3f6': 'Polygon',
    '0x553d3d295e0f695b9228246232edf400ed3560b5': 'Paxos Gold',
    '0x912ce59144191c1204e64559fe8253a0e49e6548': 'Arbitrum',
    '0x25d887ce7a35172c62febfd67a1856f20faebb00': 'Pepe',
    '0x4200000000000000000000000000000000000042': 'Optimism',
    '0xdc6ff44d5d932cbd77b52e5612ba0529dc6226f1': 'Worldcoin',
    '0xbaa5cc21fd487b8fcc2f632f3f4e8d37262a0842': 'Morpho Token',
    '0x60a3e35cc302bfa44cb288bc5a4f316fdb1adb42': 'EURC',
    '0xc7346783f5e645aa998b106ef9e7f499528673d8': 'Frax USD',
    '0xb5bedd42000b71fdde22d3ee8a79bd49a568fc8f': 'Wrapped liquid staked Ether 2.0',
    '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c': 'Wrapped BInance Coin',
    '0x43c934a845205f0b514417d757d7235b8f53f1b9': 'Stellar',
    '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82': 'PancakeSwap Token',
    '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee': 'Sonic',
    '0xec3492a2508ddf4fdc0cd76f31f340b30d1793e6': 'Colony',
    'so11111111111111111111111111111111111111111': 'Solana',
    'pumpcmxqmfrsakq5r49wcjnrayyrqmxz6ae8h7h9dfn': 'Pump.fun',
    'dfh5dzrgsvvcfdoyc2citkmrbdfrkyba4sofbpmapump': 'Pippin',
    'ed5nyywezpppiwimp8vym7sd7td3lat3q3grtwhzpjby': 'Moo Deng',
    '0x9151434b16b9763660705744891fa906f660ecc5': 'USD₮0',
    '0x79bbf4508b1391af3a0f4b30bb5fc4aa9ab0e07c': 'HeyAnon',
    '0xd3dce716f3ef535c5ff8d041c1a41c3bd89b97ae': 'Sonic USD',
    '0xd27b18915e7acc8fd6ac75db6766a80f8d2f5729': 'Pendle',
    '0x5be26527e817998a7206475496fde1e68957c5a6': 'Ondo US Dollar Yield',
    '0x4e14ec08875c88f9b0cf2a075f481eda0143d1f0': 'Wrappen TON Coin',
    '0x5a7d6b2f92c77fad6ccabd7ee0624e64907eaf3e': 'ZKsync',
}

# Address to symbol mappings (auto-generated from tokens.csv)
SYMBOL_MAPPINGS = {
    '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9': 'AAVE',
    '0x3506424f91fd33084466f402d5d97f05f8e3b4af': 'CHZ',
    '0xc00e94cb662c3520282e6f5717214004a7f26888': 'COMP',
    '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48': 'USDC',
    '0xdac17f958d2ee523a2206206994597c13d831ec7': 'USDT',
    '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599': 'WBTC',
    '0x514910771af9ca656af840dff83e8264ecf986ca': 'LINK',
    '0x111111111117dc0aa78b770fa6a738034120c302': '1INCH',
    '0xf230b790e05390fc8295f4d3f60332c93bed42e2': 'TRX',
    '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984': 'UNI',
    '0x6b175474e89094c44da98b954eedeac495271d0f': 'DAI',
    '0xc944e90c64b2c07662a292be6244bdf05cda44a7': 'GRT',
    '0x56072c95faa701256059aa122697b133aded9279': 'SKY',
    '0x6b3595068778dd592e39a122f4f5a5cf09c90fe2': 'SUSHI',
    '0x4a220e6096b25eadb88358cb44068a3248254675': 'QNT',
    '0x15d4c048f83bd7e37d49ea4c83a07267ec4203da': 'GALA',
    '0x0f5d2fb29fb7d3cfee444a200298f468908cc942': 'MANA',
    '0x3845badade8e6dff049820680d1f14bd3903a5d0': 'SAND',
    '0x0d8775f648430679a709e98d2b0cb6250d2887ef': 'BAT',
    '0x455e53cbb86018ac2b8092fdcd39d8444affc3f6': 'POL',
    '0x553d3d295e0f695b9228246232edf400ed3560b5': 'PAXG',
    '0x912ce59144191c1204e64559fe8253a0e49e6548': 'ARB',
    '0x25d887ce7a35172c62febfd67a1856f20faebb00': 'PEPE',
    '0x4200000000000000000000000000000000000042': 'OP',
    '0xdc6ff44d5d932cbd77b52e5612ba0529dc6226f1': 'WLD',
    '0xbaa5cc21fd487b8fcc2f632f3f4e8d37262a0842': 'MORPHO',
    '0x60a3e35cc302bfa44cb288bc5a4f316fdb1adb42': 'EURC',
    '0xc7346783f5e645aa998b106ef9e7f499528673d8': 'frxUSD',
    '0xb5bedd42000b71fdde22d3ee8a79bd49a568fc8f': 'wstETH',
    '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c': 'WBNB',
    '0x43c934a845205f0b514417d757d7235b8f53f1b9': 'XLM',
    '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82': 'CAKE',
    '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee': 'S',
    '0xec3492a2508ddf4fdc0cd76f31f340b30d1793e6': 'CLY',
    'so11111111111111111111111111111111111111111': 'SOL',
    'pumpcmxqmfrsakq5r49wcjnrayyrqmxz6ae8h7h9dfn': 'Pump',
    'dfh5dzrgsvvcfdoyc2citkmrbdfrkyba4sofbpmapump': 'Pippin',
    'ed5nyywezpppiwimp8vym7sd7td3lat3q3grtwhzpjby': 'MOODENG',
    '0x9151434b16b9763660705744891fa906f660ecc5': 'USD₮0',
    '0x79bbf4508b1391af3a0f4b30bb5fc4aa9ab0e07c': 'Anon',
    '0xd3dce716f3ef535c5ff8d041c1a41c3bd89b97ae': 'scUSD',
    '0xd27b18915e7acc8fd6ac75db6766a80f8d2f5729': 'PENDLE',
    '0x5be26527e817998a7206475496fde1e68957c5a6': 'USDY',
    '0x4e14ec08875c88f9b0cf2a075f481eda0143d1f0': 'TONCOIN',
    '0x5a7d6b2f92c77fad6ccabd7ee0624e64907eaf3e': 'ZK',
}

# CoinGecko ID mappings (auto-generated with common patterns)
COINGECKO_MAPPINGS = {
    'AAVE': 'aave',
    'CHZ': 'chiliz',
    'COMP': 'compound-governance-token',
    'USDC': 'usd-coin',
    'USDT': 'tether',
    'WBTC': 'wrapped-bitcoin',
    'LINK': 'chainlink',
    '1INCH': '1inch',
    'TRX': 'tron',
    'UNI': 'uniswap',
    'DAI': 'dai',
    'GRT': 'the-graph',
    'SUSHI': 'sushi',
    'QNT': 'quant-network',
    'GALA': 'gala',
    'MANA': 'decentraland',
    'SAND': 'the-sandbox',
    'BAT': 'basic-attention-token',
    'POL': 'matic-network',
    'OP': 'optimism',
    'S': 'sonic',
}

# CoinPaprika ID mappings (auto-generated with common patterns)
PAPRIKA_MAPPINGS = {
    'AAVE': 'aave-aave',
    'CHZ': 'chz-chiliz',
    'COMP': 'comp-compound',
    'USDC': 'usdc-usd-coin',
    'USDT': 'usdt-tether',
    'WBTC': 'wbtc-wrapped-bitcoin',
    'LINK': 'link-chainlink',
    '1INCH': '1inch-1inch',
    'TRX': 'trx-tron',
    'UNI': 'uni-uniswap',
    'DAI': 'dai-dai',
    'GRT': 'grt-the-graph',
    'SUSHI': 'sushi-sushiswap',
    'QNT': 'qnt-quant',
    'GALA': 'gala-gala',
    'MANA': 'mana-decentraland',
    'SAND': 'sand-the-sandbox',
    'BAT': 'bat-basic-attention-token',
    'POL': 'matic-polygon',
    'OP': 'op-optimism',
    'S': 'sonic-sonic',
}

# Market cap estimates (will be updated by APIs)
MARKET_CAP_ESTIMATES = {
    'AAVE': 0,
    'CHZ': 0,
    'COMP': 0,
    'USDC': 0,
    'USDT': 0,
    'WBTC': 0,
    'LINK': 0,
    '1INCH': 0,
    'TRX': 0,
    'UNI': 0,
    'DAI': 0,
    'GRT': 0,
    'SKY': 0,
    'SUSHI': 0,
    'QNT': 0,
    'GALA': 0,
    'MANA': 0,
    'SAND': 0,
    'BAT': 0,
    'POL': 0,
    'PAXG': 0,
    'ARB': 0,
    'PEPE': 0,
    'OP': 0,
    'WLD': 0,
    'MORPHO': 0,
    'EURC': 0,
    'frxUSD': 0,
    'wstETH': 0,
    'WBNB': 0,
    'XLM': 0,
    'CAKE': 0,
    'AVAX': 0,
    'CLY': 0,
    'SOL': 0,
    'Pump': 0,
    'Pippin': 0,
    'MOODENG': 0,
    'SEI': 0,
    'USD₮0': 0,
    'S': 0,
    'Anon': 0,
    'scUSD': 0,
    'PENDLE': 0,
    'USDY': 0,
    'TONCOIN': 0,
    'ZK': 0,
}

# Holder estimates (will be updated by APIs)
HOLDER_ESTIMATES = {
    'AAVE': 0,
    'CHZ': 0,
    'COMP': 0,
    'USDC': 0,
    'USDT': 0,
    'WBTC': 0,
    'LINK': 0,
    '1INCH': 0,
    'TRX': 0,
    'UNI': 0,
    'DAI': 0,
    'GRT': 0,
    'SKY': 0,
    'SUSHI': 0,
    'QNT': 0,
    'GALA': 0,
    'MANA': 0,
    'SAND': 0,
    'BAT': 0,
    'POL': 0,
    'PAXG': 0,
    'ARB': 0,
    'PEPE': 0,
    'OP': 0,
    'WLD': 0,
    'MORPHO': 0,
    'EURC': 0,
    'frxUSD': 0,
    'wstETH': 0,
    'WBNB': 0,
    'XLM': 0,
    'CAKE': 0,
    'AVAX': 0,
    'CLY': 0,
    'SOL': 0,
    'Pump': 0,
    'Pippin': 0,
    'MOODENG': 0,
    'SEI': 0,
    'USD₮0': 0,
    'S': 0,
    'Anon': 0,
    'scUSD': 0,
    'PENDLE': 0,
    'USDY': 0,
    'TONCOIN': 0,
    'ZK': 0,
}

# Token types (based on chain)
TOKEN_TYPES = {
    'AAVE': 'ERC-20',
    'CHZ': 'ERC-20',
    'COMP': 'ERC-20',
    'USDC': 'ERC-20',
    'USDT': 'ERC-20',
    'WBTC': 'ERC-20',
    'LINK': 'ERC-20',
    '1INCH': 'ERC-20',
    'TRX': 'ERC-20',
    'UNI': 'ERC-20',
    'DAI': 'ERC-20',
    'GRT': 'ERC-20',
    'SKY': 'ERC-20',
    'SUSHI': 'ERC-20',
    'QNT': 'ERC-20',
    'GALA': 'ERC-20',
    'MANA': 'ERC-20',
    'SAND': 'ERC-20',
    'BAT': 'ERC-20',
    'POL': 'ERC-20',
    'PAXG': 'ERC-20',
    'ARB': 'ERC-20',
    'PEPE': 'ERC-20',
    'OP': 'ERC-20',
    'WLD': 'ERC-20',
    'MORPHO': 'Unknown',
    'EURC': 'Unknown',
    'frxUSD': 'Unknown',
    'wstETH': 'Unknown',
    'WBNB': 'BEP-20',
    'XLM': 'BEP-20',
    'CAKE': 'BEP-20',
    'AVAX': 'Unknown',
    'CLY': 'Unknown',
    'SOL': 'Unknown',
    'Pump': 'Unknown',
    'Pippin': 'Unknown',
    'MOODENG': 'Unknown',
    'SEI': 'Unknown',
    'USD₮0': 'Unknown',
    'S': 'ERC-20',
    'Anon': 'ERC-20',
    'scUSD': 'ERC-20',
    'PENDLE': 'Unknown',
    'USDY': 'Unknown',
    'TONCOIN': 'Unknown',
    'ZK': 'Unknown',
}

# Helper functions
def get_token_name(address):
    """Get token name from address"""
    return ADDRESS_MAPPINGS.get(address.lower(), 'Unknown Token')

def get_token_symbol(address):
    """Get token symbol from address"""
    return SYMBOL_MAPPINGS.get(address.lower(), 'Unknown')

def get_coingecko_id(symbol):
    """Get CoinGecko ID from symbol"""
    return COINGECKO_MAPPINGS.get(symbol.upper(), None)

def get_paprika_id(symbol):
    """Get CoinPaprika ID from symbol"""
    return PAPRIKA_MAPPINGS.get(symbol.upper(), None)

def get_market_cap_estimate(symbol):
    """Get market cap estimate from symbol"""
    return MARKET_CAP_ESTIMATES.get(symbol.upper(), 0)

def get_holder_estimate(symbol):
    """Get holder estimate from symbol"""
    return HOLDER_ESTIMATES.get(symbol.upper(), 0)

def get_token_type(symbol):
    """Get token type from symbol"""
    return TOKEN_TYPES.get(symbol.upper(), 'Unknown')

# Legacy function names for backward compatibility
def get_cmc_id(symbol):
    """Get CoinMarketCap ID from symbol (placeholder)"""
    return None

def get_cmc_name(symbol):
    """Get CoinMarketCap name from symbol (placeholder)"""
    return get_token_name(symbol)

def get_cmc_slug(symbol):
    """Get CoinMarketCap slug from symbol (placeholder)"""
    return symbol.lower()
